In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

In [5]:
driver = pd.read_csv("kasirbaru.csv")
driver.head()

,id_barang,id_kategori,nama_barang,kondisi,harga_beli,harga_jual,satuan_barang,stok,tgl_input
0,PS.FLTL.001,1,full sheet Prajurit Keraton,Baru,366988,367998,PCS,10,"22 June 2022, 1:50"
1,PS.FLTL.002,1,full sheet 11th Asean Paragames solo 2022,Baru,319988,322998,PCS,10,"22 June 2022, 1:50"
2,PS.PRGK.001,2,Global Geopark Belitong,Baru,115988,117998,PCS,10,"22 June 2022, 1:50"
3,PS.PRGK.002,2,Pos Lintaas Batas Negara,Baru,111988,112998,PCS,10,"22 June 2022, 1:50"
4,PS.SHP.001,3,annual mettings 2018 IMF,Baru,108988,110998,PCS,9,"22 June 2022, 1:50"

In [6]:
driver_x = driver.iloc[:, 1:9]
driver_x.head()

,id_kategori,nama_barang,kondisi,harga_beli,harga_jual,satuan_barang,stok,tgl_input
0,1,full sheet Prajurit Keraton,Baru,366988,367998,PCS,10,"22 June 2022, 1:50"
1,1,full sheet 11th Asean Paragames solo 2022,Baru,319988,322998,PCS,10,"22 June 2022, 1:50"
2,2,Global Geopark Belitong,Baru,115988,117998,PCS,10,"22 June 2022, 1:50"
3,2,Pos Lintaas Batas Negara,Baru,111988,112998,PCS,10,"22 June 2022, 1:50"
4,3,annual mettings 2018 IMF,Baru,108988,110998,PCS,9,"22 June 2022, 1:50"

In [7]:
x_array =  np.array(driver_x)
print(x_array)

[[1 'full sheet Prajurit Keraton' 'Baru' 366988 367998 'PCS' 10
  '22 June 2022, 1:50']
 [1 'full sheet 11th Asean Paragames solo 2022' 'Baru' 319988 322998
  'PCS' 10 '22 June 2022, 1:50']
 [2 'Global Geopark Belitong' 'Baru' 115988 117998 'PCS' 10
  '22 June 2022, 1:50']
 [2 'Pos Lintaas Batas Negara' 'Baru' 111988 112998 'PCS' 10
  '22 June 2022, 1:50']
 [3 'annual mettings 2018 IMF' 'Baru' 108988 110998 'PCS' 9
  '22 June 2022, 1:50']
 [3 'tanda kehormatan 2020' 'Baru' 77988 79998 'PCS' 10
  '22 June 2022, 1:50']
 [5 'postcrossing 2017' 'Baru' 75988 77998 'PCS' 10 '22 June 2022, 1:50']
 [5 'Shio Kerbau 2021' 'Baru' 111988 112998 'PCS' 10 '22 June 2022, 1:50']
 [2 'keraton baru boko' 'Baru' 108988 110998 'PCS' 10
  '22 June 2022, 2:25']
 [3 'Sirkuit Mandalika' 'Baru' 111988 112998 'PCS' 6 '22 June 2022, 2:27']
 [4 'Baliphex 2021' 'Baru' 108988 110998 'PCS' 6 '21 June 2022, 5:28']]

In [ ]:
cols = ['id_barang',  'MEREK', 'BUATAN', 'TAHUN_BUATAN','KATEGORI', 'KONDISI','SERTIFIKASI']

df_features[cols] = df_features[cols].astype('category')

df_features.info()

In [8]:
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x_array)
x_scaled

ValueError: could not convert string to float: 'full sheet Prajurit Keraton'